In [1]:
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\RASIK AHMAD DAR\AppData\Local\Temp\ipykernel_18484\2035458946.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\RASIK AHMAD DAR\AppData\Local\Temp\ipykernel_18484\2035458946.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\RASIK AHMAD DAR\AppData\Local\Temp\ipykernel_18484\2035458946.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\RASIK AHMAD DAR\AppData\Local\Temp\ipykernel_18484\2035458946.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\RASIK AHMAD DAR\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\RASIK AHMAD DAR\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [16]:
df=pd.read_json('C:\\Users\\RASIK AHMAD DAR\\Desktop\\python basics\\DE\\pandas\\new.json')
df2=pd.DataFrame(df)
df2.insert(8,'marks',df2['age'])
df2.drop(['marks'],axis=1,inplace=True)
df2.insert(8,'notice_period',df2['age']/15)
df2.head(40)

,id,name,age,city,occupation,salary,is_active,join_date,notice_period
0,1,Alice Smith,30,New York,Engineer,90000,True,2020-05-15,2.000000
1,2,Bob Johnson,25,Los Angeles,Designer,75000,True,2021-01-20,1.666667
2,3,Charlie Brown,40,Chicago,Manager,110000,False,2018-11-01,2.666667
3,4,Diana Davis,28,Houston,Analyst,80000,True,2022-03-10,1.866667
4,5,Ethan Miller,35,Phoenix,Developer,95000,True,2019-07-05,2.333333
5,6,Fiona Wilson,23,Philadelphia,Intern,50000,True,2023-06-22,1.533333
6,7,George White,45,San Antonio,Director,130000,False,2017-02-14,3.000000
7,8,Hannah Taylor,31,San Diego,Tester,85000,True,2020-09-28,2.066667
8,9,Ian Moore,29,Dallas,Consultant,92000,True,2021-04-03,1.933333
9,10,Julia Clark,33,San Jose,Architect,100000,True,2019-12-12,2.200000
10,11,Kevin Lee,27,Austin,Marketer,78000,False,2022-07-18,1.800000
11,12,Laura King,42,Jacksonville,HR Manager,115000,True,2017-05-25,2.800000
12,13,Martin Hall,38,San Francisco,Data Scientist,120000,True,2018-08-16,2.533333
13,14,Nancy Green,26,Columbus,Accountant,70000,True,2023-03-01,1.733333
14,15,Oliver Baker,34,Indianapolis,Project Manager,105000,False,2020-10-20,2.266667
15,16,Patricia Adams,24,Charlotte,Writer,65000,True,2021-09-15,1.600000
16,17,Quinn Hill,39,Seattle,Product Owner,125000,False,2019-04-09,2.600000
17,18,Rose King,32,Denver,Sales Rep,90000,True,2022-11-30,2.133333
18,19,Samuel Young,41,Nashville,Auditor,100000,True,2018-07-10,2.733333
19,20,Tara Allen,29,Oklahoma City,Recruiter,82000,True,2023-01-28,1.933333
20,21,Victor Wright,37,Louisville,Programmer,98000,True,2020-03-15,2.466667
21,22,Wendy Scott,28,Portland,Tech Support,75000,True,2021-08-02,1.866667
22,23,Xavier Carter,43,Las Vegas,Financial Analyst,110000,False,2019-11-20,2.866667
23,24,Yara Wood,31,Milwaukee,Web Developer,92000,True,2022-06-05,2.066667
24,25,Zane Reed,36,Baltimore,Network Engineer,100000,True,2018-12-01,2.400000
25,26,Amelia Baker,27,Atlanta,UX Designer,85000,True,2023-02-18,1.800000
26,27,Benjamin Cole,40,Miami,Software Architect,120000,True,2017-09-05,2.666667
27,28,Chloe Davis,29,Raleigh,Content Creator,70000,True,2022-08-22,1.933333
28,29,Daniel Evans,33,Kansas City,Database Admin,95000,False,2021-05-10,2.200000
29,30,Emily Fox,25,Minneapolis,Graphic Designer,68000,True,2023-01-15,1.666667
30,31,Franklin Green,38,Sacramento,IT Specialist,105000,True,2018-06-28,2.533333
31,32,Grace Hall,32,St. Louis,Product Manager,115000,True,2020-11-03,2.133333
32,33,Henry Ito,26,Tampa,Social Media Mgr,72000,True,2021-07-07,1.733333
33,34,Isabella Jones,41,New Orleans,Business Analyst,100000,True,2019-10-12,2.733333
34,35,Jack Kelly,27,Cleveland,Legal Associate,78000,True,2022-04-01,1.800000
35,36,Katherine Lewis,34,Pittsburgh,Market Analyst,88000,True,2023-03-20,2.266667
36,37,Liam Moore,45,Cincinnati,Chief Engineer,130000,False,2017-03-15,3.000000
37,38,Mia Norton,30,Richmond,Financial Planner,92000,True,2020-06-11,2.000000
38,39,Noah O'Brien,29,Buffalo,Data Engineer,98000,True,2021-02-08,1.933333
39,40,Olivia Perry,36,Salt Lake City,Business Manager,110000,True,2019-08-02,2.400000

In [28]:
#i have to find the salary greater than 100000 withe names of the persons withe the salaries
# df3=df2[df2['salary']>100000]
# print(df3[['id','name','city','occupation','salary','is_active','join_date','notice_period']])
df4=df2[df2['is_active']==True]
df4.head(40)
total_salary=df2['salary'].sum()
print(total_salary)

92314.60674157304

In [5]:
age=df2[df2['age']>30]
print(age[['name','age']])

                  name  age
2        Charlie Brown   40
4         Ethan Miller   35
6         George White   45
7        Hannah Taylor   31
9          Julia Clark   33
11          Laura King   42
12         Martin Hall   38
14        Oliver Baker   34
16          Quinn Hill   39
17           Rose King   32
18        Samuel Young   41
20       Victor Wright   37
22       Xavier Carter   43
23           Yara Wood   31
24           Zane Reed   36
26       Benjamin Cole   40
28        Daniel Evans   33
30      Franklin Green   38
31          Grace Hall   32
33      Isabella Jones   41
35     Katherine Lewis   34
36          Liam Moore   45
39        Olivia Perry   36
41      Penelope Reyes   40
42       Quentin Scott   31
44    Samuel Underwood   35
46      Ulysses Wagner   39
47         Violet Wood   33
49         Xena Zamora   44
50        Ava Martinez   32
52        Clara Nelson   38
54       Ella Peterson   36
55    Finnigan Roberts   31
56        Gwen Simmons   42
58          Ivy Torres   33
59      John Underwood   40
61          Leo Walker   37
63          Max Wilson   35
65         Oscar Adams   41
67         Quincy Cook   34
68         Riley Davis   38
70      Thomas Fischer   33
71           Uma Green   45
73           Wendy Ito   36
74        Xavier Jones   31
76          Zane Lewis   32
78     Benjamin Norton   37
80        Daniel Perry   41
82      Franklin Reyes   35
84        Henry Taylor   33
85  Isabella Underwood   44
87    Katherine Wagner   39
88           Liam Wood   31

In [6]:
age=df2[df2['age']>30]
print(age[['name','age']])

                  name  age
2        Charlie Brown   40
4         Ethan Miller   35
6         George White   45
7        Hannah Taylor   31
9          Julia Clark   33
11          Laura King   42
12         Martin Hall   38
14        Oliver Baker   34
16          Quinn Hill   39
17           Rose King   32
18        Samuel Young   41
20       Victor Wright   37
22       Xavier Carter   43
23           Yara Wood   31
24           Zane Reed   36
26       Benjamin Cole   40
28        Daniel Evans   33
30      Franklin Green   38
31          Grace Hall   32
33      Isabella Jones   41
35     Katherine Lewis   34
36          Liam Moore   45
39        Olivia Perry   36
41      Penelope Reyes   40
42       Quentin Scott   31
44    Samuel Underwood   35
46      Ulysses Wagner   39
47         Violet Wood   33
49         Xena Zamora   44
50        Ava Martinez   32
52        Clara Nelson   38
54       Ella Peterson   36
55    Finnigan Roberts   31
56        Gwen Simmons   42
58          Ivy Torres   33
59      John Underwood   40
61          Leo Walker   37
63          Max Wilson   35
65         Oscar Adams   41
67         Quincy Cook   34
68         Riley Davis   38
70      Thomas Fischer   33
71           Uma Green   45
73           Wendy Ito   36
74        Xavier Jones   31
76          Zane Lewis   32
78     Benjamin Norton   37
80        Daniel Perry   41
82      Franklin Reyes   35
84        Henry Taylor   33
85  Isabella Underwood   44
87    Katherine Wagner   39
88           Liam Wood   31

In [33]:
eng=df2[df2['occupation']=='Engineer']
print(eng[['name','id','salary']])

          name  id  salary
0  Alice Smith   1   90000